version: "3.8"
services:
  db:
    image: postgres
    container_name: pgDB
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: csesoc
      POSTGRES_PASSWORD: bot
      POSTGRES_DB: botdb
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: pass
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data:
